//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceConventionClient {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanceConventionClient.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string CameraButton {
            get {
                return ResourceManager.GetString("CameraButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not signed up for currently active competitions.
        /// </summary>
        public static string CameraPageErrorBody {
            get {
                return ResourceManager.GetString("CameraPageErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was checked-in..
        /// </summary>
        public static string CameraPageSuccessBody {
            get {
                return ResourceManager.GetString("CameraPageSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string CameraPageSuccessNo {
            get {
                return ResourceManager.GetString("CameraPageSuccessNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string CameraPageSuccessYes {
            get {
                return ResourceManager.GetString("CameraPageSuccessYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning QR Code.
        /// </summary>
        public static string CameraPageTitle {
            get {
                return ResourceManager.GetString("CameraPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string CodePageTitle {
            get {
                return ResourceManager.GetString("CodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string ContestPageHeader {
            get {
                return ResourceManager.GetString("ContestPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contests available for check-in.
        /// </summary>
        public static string ContestPageInfo {
            get {
                return ResourceManager.GetString("ContestPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest check-in.
        /// </summary>
        public static string CurrentEventPageContestButton {
            get {
                return ResourceManager.GetString("CurrentEventPageContestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My registration.
        /// </summary>
        public static string CurrentEventPageRegButton {
            get {
                return ResourceManager.GetString("CurrentEventPageRegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration desk.
        /// </summary>
        public static string CurrentEventPageRegDeskButton {
            get {
                return ResourceManager.GetString("CurrentEventPageRegDeskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string CurrentEventPageTitle {
            get {
                return ResourceManager.GetString("CurrentEventPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ErrorAnswer {
            get {
                return ResourceManager.GetString("ErrorAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danceConvention.net.
        /// </summary>
        public static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageLogButton {
            get {
                return ResourceManager.GetString("LoginPageLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageLoginLabel {
            get {
                return ResourceManager.GetString("LoginPageLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPagePasswordLabel {
            get {
                return ResourceManager.GetString("LoginPagePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Events.
        /// </summary>
        public static string MyEventsPageCurrentHeader {
            get {
                return ResourceManager.GetString("MyEventsPageCurrentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Events.
        /// </summary>
        public static string MyEventsPagePastHeader {
            get {
                return ResourceManager.GetString("MyEventsPagePastHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyEvents.
        /// </summary>
        public static string MyEventsPageTitle {
            get {
                return ResourceManager.GetString("MyEventsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        public static string NoResultsInfo {
            get {
                return ResourceManager.GetString("NoResultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string ProfilePageLogoutButton {
            get {
                return ResourceManager.GetString("ProfilePageLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to undo this check-in?.
        /// </summary>
        public static string RegDeskConfirmBody {
            get {
                return ResourceManager.GetString("RegDeskConfirmBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string RegDeskConfirmNo {
            get {
                return ResourceManager.GetString("RegDeskConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string RegDeskConfirmTitle {
            get {
                return ResourceManager.GetString("RegDeskConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string RegDeskConfirmYes {
            get {
                return ResourceManager.GetString("RegDeskConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string RegDeskPageAmount {
            get {
                return ResourceManager.GetString("RegDeskPageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment  .
        /// </summary>
        public static string RegDeskPageComment {
            get {
                return ResourceManager.GetString("RegDeskPageComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL AMOUNTS DISPLAYED IN:.
        /// </summary>
        public static string RegDeskPageCurrency {
            get {
                return ResourceManager.GetString("RegDeskPageCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter participant name or scan QR code.
        /// </summary>
        public static string RegDeskPageInfo {
            get {
                return ResourceManager.GetString("RegDeskPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owed:.
        /// </summary>
        public static string RegDeskPageOwed {
            get {
                return ResourceManager.GetString("RegDeskPageOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Payment.
        /// </summary>
        public static string RegDeskPagePaymentButton {
            get {
                return ResourceManager.GetString("RegDeskPagePaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payment amount.
        /// </summary>
        public static string RegDeskPaymentError {
            get {
                return ResourceManager.GetString("RegDeskPaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level changed to information.
        /// </summary>
        public static string SettingsPageInfoInformation {
            get {
                return ResourceManager.GetString("SettingsPageInfoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL changed to: .
        /// </summary>
        public static string SettingsPageInfoUrl {
            get {
                return ResourceManager.GetString("SettingsPageInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level changed to verbose.
        /// </summary>
        public static string SettingsPageInfoVerbose {
            get {
                return ResourceManager.GetString("SettingsPageInfoVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Error.
        /// </summary>
        public static string SettingsPageReportButton {
            get {
                return ResourceManager.GetString("SettingsPageReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SettingsPageSubmitButton {
            get {
                return ResourceManager.GetString("SettingsPageSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string SettingsPageUrlLabel {
            get {
                return ResourceManager.GetString("SettingsPageUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose logging.
        /// </summary>
        public static string SettingsPageVerboseSwitchLabel {
            get {
                return ResourceManager.GetString("SettingsPageVerboseSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Info.
        /// </summary>
        public static string UserRegPageHeader {
            get {
                return ResourceManager.GetString("UserRegPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced:.
        /// </summary>
        public static string UserRegPageInvoiced {
            get {
                return ResourceManager.GetString("UserRegPageInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid:.
        /// </summary>
        public static string UserRegPagePaid {
            get {
                return ResourceManager.GetString("UserRegPagePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event pass.
        /// </summary>
        public static string UserRegPagePass {
            get {
                return ResourceManager.GetString("UserRegPagePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration QR Code.
        /// </summary>
        public static string UserRegPageQrButton {
            get {
                return ResourceManager.GetString("UserRegPageQrButton", resourceCulture);
            }
        }
    }
}
