//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceConventionClient {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanceConventionClient.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        public static string CompetitorsPageInfo {
            get {
                return ResourceManager.GetString("CompetitorsPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string ContestPageCameraButton {
            get {
                return ResourceManager.GetString("ContestPageCameraButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string ContestPageHeader {
            get {
                return ResourceManager.GetString("ContestPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contests available for check-in.
        /// </summary>
        public static string ContestPageInfo {
            get {
                return ResourceManager.GetString("ContestPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest check-in.
        /// </summary>
        public static string CurrentEventPageContestButton {
            get {
                return ResourceManager.GetString("CurrentEventPageContestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My registration.
        /// </summary>
        public static string CurrentEventPageRegButton {
            get {
                return ResourceManager.GetString("CurrentEventPageRegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration desk.
        /// </summary>
        public static string CurrentEventPageRegDeskButton {
            get {
                return ResourceManager.GetString("CurrentEventPageRegDeskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string CurrentEventPageTitle {
            get {
                return ResourceManager.GetString("CurrentEventPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danceConvention.net.
        /// </summary>
        public static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageLogButton {
            get {
                return ResourceManager.GetString("LoginPageLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageLoginLabel {
            get {
                return ResourceManager.GetString("LoginPageLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPagePasswordLabel {
            get {
                return ResourceManager.GetString("LoginPagePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Events.
        /// </summary>
        public static string MyEventsPageCurrentHeader {
            get {
                return ResourceManager.GetString("MyEventsPageCurrentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Events.
        /// </summary>
        public static string MyEventsPagePastHeader {
            get {
                return ResourceManager.GetString("MyEventsPagePastHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyEvents.
        /// </summary>
        public static string MyEventsPageTitle {
            get {
                return ResourceManager.GetString("MyEventsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string ProfilePageLogoutButton {
            get {
                return ResourceManager.GetString("ProfilePageLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level changed to information.
        /// </summary>
        public static string SettingsPageInfoInformation {
            get {
                return ResourceManager.GetString("SettingsPageInfoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL changed to: .
        /// </summary>
        public static string SettingsPageInfoUrl {
            get {
                return ResourceManager.GetString("SettingsPageInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level changed to verbose.
        /// </summary>
        public static string SettingsPageInfoVerbose {
            get {
                return ResourceManager.GetString("SettingsPageInfoVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Error.
        /// </summary>
        public static string SettingsPageReportButton {
            get {
                return ResourceManager.GetString("SettingsPageReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SettingsPageSubmitButton {
            get {
                return ResourceManager.GetString("SettingsPageSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string SettingsPageUrlLabel {
            get {
                return ResourceManager.GetString("SettingsPageUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose logging.
        /// </summary>
        public static string SettingsPageVerboseSwitchLabel {
            get {
                return ResourceManager.GetString("SettingsPageVerboseSwitchLabel", resourceCulture);
            }
        }
    }
}
